theme: jekyll-theme-minimal
title: Should We Use an Abstract Comic Form to Persuade? Experiments with Online Charitable Donation
description: A short description of your site's purpose
show_downloads: [true]